spring:
  application:
    name: w-ai-coder-helper-backend
  profiles:
    active: local

# AI 模型
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: xxx
      embedding-model:
        model-name: text-embedding-v4
        api-key: xxx

bigmodel:
  api-key: <Your Api Key>

